disabled_rules:
 - todo
 - line_length
 - cyclomatic_complexity
 - type_body_length
 - function_body_length
 - file_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
